#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        # Clean up global library directory and downloaded packages
        if [ -d /usr/local/lib/lang ]; then
            rm -rf /usr/local/lib/lang
            echo "Cleaned up /usr/local/lib/lang"
        fi
        ;;

    upgrade|failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0

